### ISSUE TITLE
英文中有“顿号”吗？

### ISSUE THREAD

**Issue by kangchenyun** [generalized-intelligence/Chinese-Sytle-Guide#2]
在该指南的“英文”部分，有这样一条“逗号、顿号、句号、感叹号、问号后留一个空格”，请问英文中有顿号吗？

**Comment by lawrencelry** [comment]
Thanks, we've fixed this.

**Comment by kangchenyun** [comment]
所以，三年前的一份文档，现在公开，这种错误还未纠正，gi 真的在践行这份指南吗？

**Comment by MasterPa** [comment]
正如我在介绍这份指南的节目中所说，我们践行的不够好。

**Comment by kangchenyun** [comment]
You can avoid this just by reading it **carefully**, I feel bad for Lawrence.
