### ISSUE TITLE
中英文引号的特殊情况

### ISSUE THREAD

**Issue by NLasagna** [generalized-intelligence/Chinese-Sytle-Guide#6]
请问你们有没有考虑过如下情况：

中文段落中引用用英文，应该使用哪种引号？

中文段落决定完全使用中文引号，其中的英文前后是否需要空格？

**Comment by lawrencelry** [comment]
你好，在中文段落裡引用英文應該用「」。例如：

為什麼很多人不知道「tell me about it」在口語裡的意思？

只要用了「」『』引號，由於它的寬度是按照漢字寬度設計的，所以這兩對引號的兩端無論是什麼，都不需要空格。（不知道我對您第二個問題的理解對不對。）

**Comment by NLasagna** [comment]
> 你好，在中文段落裡引用英文應該用「」。例如： 為什麼很多人不知道「tell me about it」在口語裡的意思？ 只要用了「」『』引號，由於它的寬度是按照漢字寬度設計的，所以這兩對引號的兩端無論是什麼，都不需要空格。（不知道我對您第二個問題的理解對不對。）
> […](#)

了解，明白了。
